from __future__ import annotations

from pathlib import Path

import yaml

from app.models.schemas import DecisionConfig, JobRecord
from app.services.project_writer import write_text


def _model_py(job: JobRecord, decision_config: DecisionConfig) -> str:
    model_name = decision_config.model.selected
    return f'''"""
Baseline model generated by Paper2Project.
Paper title: {job.parsed_paper.title if job.parsed_paper else "Unknown"}
Reference note: model choice may be a baseline substitute for the paper architecture.
"""

import torch
from torch import nn


class PaperModel(nn.Module):
    def __init__(self, vocab_size: int = 30522, embed_dim: int = 128, num_classes: int = 4):
        super().__init__()
        # Paper-inspired baseline. Replace with a closer architecture if needed.
        self.embedding = nn.Embedding(vocab_size, embed_dim)
        self.encoder = nn.GRU(embed_dim, embed_dim, batch_first=True)
        self.classifier = nn.Linear(embed_dim, num_classes)

    def forward(self, input_ids: torch.Tensor) -> torch.Tensor:
        embedded = self.embedding(input_ids)
        _, hidden = self.encoder(embedded)
        logits = self.classifier(hidden[-1])
        return logits


MODEL_NAME = "{model_name}"
'''


def _data_loader_py(decision_config: DecisionConfig) -> str:
    dataset_name = decision_config.dataset.selected
    return f'''"""
Dataset loader generated by Paper2Project.
Selected dataset: {dataset_name}
"""

from datasets import load_dataset
from torch.utils.data import DataLoader


def load_text_dataset():
    dataset = load_dataset("{dataset_name}")
    return dataset


def build_dataloaders(tokenizer_fn, batch_size: int):
    dataset = load_text_dataset()
    train_split = dataset["train"]
    eval_split = dataset["test"] if "test" in dataset else dataset["train"]

    def collate_fn(batch):
        texts = [item.get("text", "") for item in batch]
        labels = [int(item.get("label", 0)) for item in batch]
        token_ids = tokenizer_fn(texts)
        return token_ids, labels

    train_loader = DataLoader(train_split, batch_size=batch_size, shuffle=True, collate_fn=collate_fn)
    eval_loader = DataLoader(eval_split, batch_size=batch_size, shuffle=False, collate_fn=collate_fn)
    return train_loader, eval_loader
'''


def _train_py(job: JobRecord, decision_config: DecisionConfig) -> str:
    return f'''"""
Training entrypoint generated by Paper2Project.
Task guess: {job.analysis.task if job.analysis else "unknown"}
Loss guess: {job.analysis.loss if job.analysis else "unknown"}
"""

import random

import numpy as np
import torch
from torch import nn
from torch.optim import AdamW

from data_loader import build_dataloaders
from model import PaperModel


def set_seed(seed: int) -> None:
    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    torch.cuda.manual_seed_all(seed)


def simple_tokenizer(texts, max_length: int = 128):
    encoded = []
    for text in texts:
        tokens = [min(ord(ch), 255) for ch in text[:max_length]]
        tokens += [0] * (max_length - len(tokens))
        encoded.append(tokens)
    return torch.tensor(encoded, dtype=torch.long)


def evaluate(model, dataloader, device):
    model.eval()
    total = 0
    correct = 0
    with torch.no_grad():
        for inputs, labels in dataloader:
            inputs = inputs.to(device)
            labels = torch.tensor(labels, dtype=torch.long, device=device)
            logits = model(inputs)
            predictions = logits.argmax(dim=-1)
            total += labels.numel()
            correct += int((predictions == labels).sum().item())
    return {{"accuracy": (correct / total) if total else 0.0}}


def main():
    config = {decision_config.training.model_dump()}
    set_seed(config["seed"])
    device = "cuda" if torch.cuda.is_available() else "cpu"
    model = PaperModel().to(device)
    optimizer = AdamW(model.parameters(), lr=config["learning_rate"])
    criterion = nn.CrossEntropyLoss()
    train_loader, eval_loader = build_dataloaders(simple_tokenizer, config["batch_size"])

    for epoch in range(config["epochs"]):
        model.train()
        for inputs, labels in train_loader:
            inputs = inputs.to(device)
            labels = torch.tensor(labels, dtype=torch.long, device=device)
            optimizer.zero_grad()
            logits = model(inputs)
            loss = criterion(logits, labels)
            loss.backward()
            optimizer.step()
        metrics = evaluate(model, eval_loader, device)
        print({{"epoch": epoch + 1, "metrics": metrics}})


if __name__ == "__main__":
    main()
'''


def _generated_readme(job: JobRecord) -> str:
    title = job.parsed_paper.title if job.parsed_paper else "Unknown paper"
    return f"""# Generated Project

This project was generated from:

- Paper: {title}

Files:

- `model.py`
- `data_loader.py`
- `train.py`
- `config.yaml`

This is a reproducible baseline, not a guaranteed faithful reproduction.
Review assumptions before relying on the implementation.
"""


def build_generated_project(job: JobRecord, output_dir: Path, decision_config: DecisionConfig) -> list[str]:
    output_dir.mkdir(parents=True, exist_ok=True)
    files = {
        "model.py": _model_py(job, decision_config),
        "data_loader.py": _data_loader_py(decision_config),
        "train.py": _train_py(job, decision_config),
        "README.md": _generated_readme(job),
    }
    written_files: list[str] = []
    for filename, content in files.items():
        path = output_dir / filename
        write_text(path, content)
        written_files.append(str(path))

    config_path = output_dir / "config.yaml"
    config_payload = {
        "paper_title": job.parsed_paper.title if job.parsed_paper else "",
        "dataset": decision_config.dataset.model_dump(),
        "model": decision_config.model.model_dump(),
        "training": decision_config.training.model_dump(),
        "assumptions": decision_config.assumptions,
    }
    write_text(config_path, yaml.safe_dump(config_payload, sort_keys=False))
    written_files.append(str(config_path))
    return written_files
